version: '3'

services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: onga_user
      DATABASE_PASSWORD: onsato0507
      DATABASE_NAME: mydatabase
    depends_on:
      - db

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: yuzuLEO0507!
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: